-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 22:42:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sugestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sugestao` (
  `id_sugestao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mensagem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sugestao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` cadastro` (
  `id cadastro` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id cadastro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doacoes` (
  `id_doacoes` INT NOT NULL AUTO_INCREMENT,
  `tipo_doacao` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mensagem` VARCHAR(45) NULL,
  `cadastro_id_cadastro` INT NOT NULL,
  ` cadastro_id cadastro` INT NOT NULL,
  PRIMARY KEY (`id_doacoes`, `cadastro_id_cadastro`, ` cadastro_id cadastro`),
  INDEX `fk_doacoes_ cadastro_idx` (` cadastro_id cadastro` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_ cadastro`
    FOREIGN KEY (` cadastro_id cadastro`)
    REFERENCES `mydb`.` cadastro` (`id cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
